name: Deploying Springboot(War) to Tomcat on Azure Windows Server

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-stage:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'
          cache: 'maven'

      - name: Verify Java Version
        run: java -version

      - name: Download the Code
        uses: actions/checkout@v3

      - name: modify pom.xml with version
        run: sed -i "s/VERSION_NUMBER/${{ github.run_number }}/g" pom.xml

      - name: Build the Code
        run: chmod +x ./mvnw && ./mvnw package

      - name: Verify the Build is Created or Not
        run: ls -l target/*.war

      - name: upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: artifact-1
          path: target/*.war
  
  
  deploy-stage:
    name: Deployment
    runs-on: ubuntu-latest
    needs: build-stage
    steps:
      - name: Transfer file
        uses: mdallasanta/ssh-scp-deploy@3898ca4aab25b988c09e51bacdd43c522c0fb319
        with:
          host: ${{ secrets.HOST }}
          user: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          local: artifact-1/*.war
          remote: "C:/Program Files/Apache Software Foundation/Tomcat 10.1/webapps/apiservice.war"
          post_upload: Powershell.exe 'ls -l C:\Program Files\Apache Software Foundation\Tomcat 10.0\webapps\*.war'
