name: Deploying Springboot(War) to Tomcat on Azure Windows Server

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build-springboot-app:
    name: Build Springboot Application
    runs-on: ubuntu-latest
    steps:
#      - name: TEt
#        run: echo ${{ secrets.HOST }} && echo ${{ secrets.USERNAME }} && echo ${{ secrets.PASSWORD }}
      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: Verify Java Version
        run: java -version

      - name: Download the Code
        uses: actions/checkout@v3

      - name: Build the Code
        run: chmod +x ./mvnw && ./mvnw package

      - name: Verify the Build is Created or Not
        run: ls -l target/*.war

      - name: Deploy the Build to Tomcat
        uses: mdallasanta/ssh-scp-deploy@3898ca4aab25b988c09e51bacdd43c522c0fb319
        with:
          host: 40.76.142.120
          user: "MohammedAlhalwachi1"
          password: "MohammedAlhalwachi1"
          local: "./target/apiservice-0.0.1-SNAPSHOT.war"
          remote: "C:/Program Files/Apache Software Foundation/Tomcat 10.1/webapps/apiservice.war"
